---
title: "seurat_practice.Rmd"
output: html_document
date: "2025-10-08"
---

```{r setup, include=FALSE}
library(Seurat)
library(dplyr)

# Creating folder and reading in data
outdir <- "~/single_cell_practice"
outdir <- path.expand(outdir)  
if (!dir.exists(outdir)) {
  dir.create(outdir, recursive = TRUE)
}

data_file <- file.path(outdir, "pbmc3k_filtered_gene_bc_matrices.tar.gz")
download.file(
  url = "https://cf.10xgenomics.com/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz",
  destfile = data_file,
  mode = "wb"
)
untar(data_file, exdir = outdir)
data_dir <- file.path(outdir, "filtered_gene_bc_matrices", "hg19")

##################################################
pbmc.data <- Read10X(data.dir = data_dir)

pbmc <- CreateSeuratObject(
  counts = pbmc.data,
  project = "pbmc3k",
  min.cells = 3,
  min.features = 200
)
```

Question 1
```{r}
#Calculate mitochondrial percentage (pattern = "^MT-") as percent.mt

# Calculate ribosomal percentage (pattern = "^RP[SL]") as percent.rb

# Create a violin plot of nFeature_RNA, nCount_RNA, percent.mt, percent.rb


# How many cells are in the original object?
ncol(pbmc)

# Filter for nFeature_RNA > 200, nFeature_RNA < 2500, percent.mt < 5, percent.rb < 45


# How many cells remain?
```

Question 2
```{r}
# Plot FeatureScatter of percent.rb and percent.mt


# Log normalize the data, but set the scale factor to 1,000,000 (counts per million)
```


Question 3
```{r}
# Find the top 3000 variable features

# Identify the 20 most highly variable genes

# plot variable features with and without labels

```

Question 4
```{r}
# Scale data and perform PCA
```

Question 5
```{r}
# Plot DimHeatmap of the first 20 PCs and top 500 cells

# Plot elbow plot of the PCs
```

Question 6
```{r}
# Run FindNeighbors with 7 PCs

# Run FindClusters with resolution of 0.8
```

Question 7
```{r}
# Run the UMAP using 7 PCs. Also change n.neighbors to 20. ?RunUMAP for help

# Plot UMAP
```

Question 8
```{r}
# Find the top markers in cluster 2

```


Question 9
```{r}
# Store top 5 markers in a list. Hint: Use head on the cluster2.markers.
# Then, use top5 <- c("Gene1", "Gene2".....) to store the top 5 markers.
```

Question 10
```{r}
# Plot the top 5 cluster 2 markers on a violin plot and on the UMAP

```


Challenge
```{r}
## CHALLENGE: Use the AddModuleScore function to add a signature score of the top 5 markers. Use ?AddModuleScore 
# for help and name it Cluster2_Score


# Plot this feature on the UMAP. Note: Check colnames(pbmc@meta.data). Seurat may have added a "1" after the name
# of your score
# Visualize on UMAP
```

